#!/usr/bin/env python3

import re
import csv
import operator

error_messages = {}
per_user = {}
logfile = "/home/student-00-42d4bf8a6f3f/syslog.log"
pattern = r"(INFO|ERROR) ([\w' ]+|[\w\[\]#' ]+) (\w+|\w+\.\w+)$"

with open(logfile, "r") as f:
    for line in f:
        result = re.search(pattern, line)
        if result is None:
            continue
        if result.groups()[0] == "INFO":
            category = result.groups()[0]
            message = result.groups()[1]
            name = str(result.groups()[2])[1:-1]
            if name in per_user:
                user = per_user[name]
                user[category] += 1
            else:
                per_user[name] = {'INFO': 1, 'ERROR': 0}
        if result.groups()[0] == "ERROR":
            category = result.groups()[0]
            message = result.groups()[1]
            name = str(result.groups()[2])[1:-1]
            error_messages[message] = error_messages.get(message, 0) + 1
            if name in per_user:
                user = per_user[name]
                user[category] += 1
            else:
                per_user[name] = {'INFO': 0, 'ERROR': 1}

sorted_messages = [("Error", "Count")] + sorted(error_messages.items(), key=operator.itemgetter(1), reverse=True)
sorted_users = [("student-00-42d4bf8a6f3f", "INFO", "ERROR")] + sorted(per_user.items())[0:8]

with open("error_message.csv", "w") as error_file:
    writer = csv.writer(error_file)
    writer.writerows(sorted_messages)

with open("user_statistics.csv", "w") as user_file:
    writer = csv.writer(user_file)
    writer.writerows(sorted_users)
